version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/recruitment-pipeline
    ports:
      - 8000:8000
    image: app:recruitment-pipeline
    container_name: recruitment-pipeline-container
    command: python manage.py runserver 0.0.0.0:8000
    
