# Generated by Django 3.2.12 on 2023-04-10 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_accepting_applicant', models.BooleanField(default=True)),
                ('maximum_head_count', models.IntegerField(default=1)),
            ],
        ),
    ]
