# Generated by Django 4.0.2 on 2022-02-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('resume', models.BinaryField()),
                ('stage', models.CharField(choices=[('pending', 'PENDING'), ('reviewing', 'REVIEWING'), ('shortlisted', 'SHORTLISTED'), ('interviewing', 'INTERVIEWING'), ('advanced_interviewing', 'ADVANCED INTERVIEWING'), ('rejected', 'REJECTED'), ('offered', 'OFFERED'), ('hired', 'HIRED')], default='pending', max_length=150)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.jobdetails')),
            ],
        ),
    ]
