# Generated by Django 3.2.12 on 2023-02-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
        ('candidate', '0007_auto_20230205_0112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateProfile',
            new_name='CandidateJobStatus',
        ),
    ]
