# Generated by Django 3.2.12 on 2023-02-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_rename_candidateprofile_candidatejobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetailedprofile',
            name='total_relevant_years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatedetailedprofile',
            name='total_years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
