# Generated by Django 3.2.12 on 2023-02-05 01:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20230205_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
