# Generated by Django 3.2.12 on 2023-02-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_visa_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visa',
            name='validity_in_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visa',
            name='validity_in_years',
            field=models.IntegerField(default=0),
        ),
    ]
