# Generated by Django 3.2.12 on 2023-02-05 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_auto_20230205_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejobstatus',
            name='candidate',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatedetailedprofile'),
            preserve_default=False,
        ),
    ]
