# Generated by Django 3.2.12 on 2023-02-05 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_candidatejobstatus_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejobstatus',
            name='candidate',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatedetailedprofile'),
        ),
    ]
